name: Environment Deployments

on:
  push:
    branches: [ develop, staging, main ]
    paths:
      - '**.tf'
      - '**.tfvars'
      - '.github/workflows/environment-deployments.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - development
          - staging
          - production
      action:
        description: 'Terraform action to perform'
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  # Development environment
  deploy-development:
    if: github.ref == 'refs/heads/develop' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'development')
    uses: ./.github/workflows/reusable-terraform.yml
    with:
      action: ${{ github.event.inputs.action || (github.ref == 'refs/heads/develop' && 'apply') || 'plan' }}
      environment: development
      working-directory: .
      auto-approve: ${{ github.ref == 'refs/heads/develop' || github.event.inputs.action == 'destroy' }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      TF_STATE_STORAGE_ACCOUNT: ${{ secrets.TF_STATE_STORAGE_ACCOUNT }}
      TF_STATE_CONTAINER: ${{ secrets.TF_STATE_CONTAINER }}
      TF_STATE_KEY: ${{ secrets.TF_STATE_KEY }}

  # Staging environment
  deploy-staging:
    if: github.ref == 'refs/heads/staging' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'staging')
    uses: ./.github/workflows/reusable-terraform.yml
    with:
      action: ${{ github.event.inputs.action || (github.ref == 'refs/heads/staging' && 'apply') || 'plan' }}
      environment: staging
      working-directory: .
      auto-approve: ${{ github.ref == 'refs/heads/staging' || github.event.inputs.action == 'destroy' }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      TF_STATE_STORAGE_ACCOUNT: ${{ secrets.TF_STATE_STORAGE_ACCOUNT }}
      TF_STATE_CONTAINER: ${{ secrets.TF_STATE_CONTAINER }}
      TF_STATE_KEY: ${{ secrets.TF_STATE_KEY }}

  # Production environment
  deploy-production:
    if: github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production')
    uses: ./.github/workflows/reusable-terraform.yml
    with:
      action: ${{ github.event.inputs.action || (github.ref == 'refs/heads/main' && 'apply') || 'plan' }}
      environment: production
      working-directory: .
      auto-approve: ${{ github.ref == 'refs/heads/main' || github.event.inputs.action == 'destroy' }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      TF_STATE_STORAGE_ACCOUNT: ${{ secrets.TF_STATE_STORAGE_ACCOUNT }}
      TF_STATE_CONTAINER: ${{ secrets.TF_STATE_CONTAINER }}
      TF_STATE_KEY: ${{ secrets.TF_STATE_KEY }}